services:
  web:
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
      - ./xsd:/app/xsd:ro
      - ./alembic:/app/alembic:ro
    environment:
      - ENVIRONMENT=development
